import turtle 
my_turtle=turtle.Turtle()
my_turtle.color("black")
my_turtle.fillcolor("red")
my_turtle.begin_fill()
my_turtle.forward(50)
my_turtle.right(90)
my_turtle.forward(100)
my_turtle.right(90)
my_turtle.forward(100)
my_turtle.right(90)
my_turtle.forward(100)
my_turtle.right(90)
my_turtle.forward(50)
my_turtle.left(90)
my_turtle.forward(50)
my_turtle.end_fill()
turtle.done()